# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build a debug APK"
  lane :debug do
    gradle(task: "clean assembleDebug")
    slack_apk_build()
  end

 desc "Build a signed release APK & deploy to slack"
  lane :slack_apk_build do
    gradle(
      task: "assemble",
      build_type: "Release",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "D:\\project\\BaseProject\\citiustechkey.jks",
        "android.injected.signing.store.password" => "Healthcare",
        "android.injected.signing.key.alias" => "Healthcare",
        "android.injected.signing.key.password" => "Healthcare",
      }
    )
  end

end
